version: '3.8'

services:
  dialog-app:
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /usr/bin/dialogs
    restart: on-failure
    environment:
      - PORT=8081
      - PGHOST=master
      - PGPORT=5433
      - MIGR_DIR=/usr/bin/migrations
      - TARANTOOL_HOST=tarantool_master
      - TARANTOOL_PORT=3303
      - TARANTOOL_USER=user
      - TARANTOOL_PASSWORD=password
    ports:
      - "8080-8085:8080"
    depends_on:
      - master
      - tarantool-dialog
  tarantool-dialog:
    build:
      dockerfile: tarantool/Dockerfile
      context: .
    image: tarantool/tarantool:2.11.0
    restart: always
    environment:
      - TARANTOOL_USER_NAME=user
      - TARANTOOL_USER_PASSWORD=password
    ports:
      - "3303:3301"
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master_dialog"
    image: "citusdata/citus:11.3.0"
    ports: [ "${COORDINATOR_EXTERNAL_PORT:-5433}:5432" ]
    labels: [ "com.citusdata.role=Master" ]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  worker:
    image: "citusdata/citus:11.3.0"
    labels: [ "com.citusdata.role=Worker" ]
    deploy:
      replicas: 2
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager_dialog"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [ master ]
    environment: *AUTH
volumes:
  healthcheck-volume:
