version: '3.8'

services:
  dialog:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dialog.rule=Host(`localhost`)"
      - "traefik.http.routers.dialog.rule=PathPrefix(`/dialog`)"
      - "traefik.http.routers.dialog.entrypoints=web"
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /usr/bin/dialogs
    restart: on-failure
    networks:
      - dialog
      - socialnethl_social
    environment:
      - PORT=8080
      - PGHOST=master
      - PGPORT=5432
      - MIGR_DIR=/usr/bin/migrations
      - TARANTOOL_HOST=tarantool-dialog
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER=user
      - TARANTOOL_PASSWORD=password
      - KAFKA_BROKER_HOST=kafka
      - RPC_SERVER_HOST=social
    ports:
      - "8082:8080"
    depends_on:
      - master
      - tarantool-dialog
  tarantool-dialog:
    build:
      dockerfile: tarantool/Dockerfile
      context: .
    image: tarantool/tarantool:2.11.0
    restart: always
    networks:
      - dialog
    environment:
      - TARANTOOL_USER_NAME=user
      - TARANTOOL_USER_PASSWORD=password
    ports:
      - "3303:3301"
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master_dialog"
    image: "citusdata/citus:11.3.0"
    ports: [ "${COORDINATOR_EXTERNAL_PORT:-5433}:5432" ]
    labels: [ "com.citusdata.role=Master" ]
    networks:
      - dialog
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  worker:
    image: "citusdata/citus:11.3.0"
    labels: [ "com.citusdata.role=Worker" ]
    networks:
      - dialog
    deploy:
      replicas: 2
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager_dialog"
    image: "citusdata/membership-manager:0.3.0"
    networks:
      - dialog
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [ master ]
    environment: *AUTH

volumes:
  healthcheck-volume:

networks:
  dialog:
  socialnethl_social:
    external: true

